# Generated by Django 5.2.3 on 2025-06-22 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPG, JPEG, PNG 파일만 업로드 가능합니다.', upload_to='fabric_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '옷 이미지',
                'verbose_name_plural': '옷 이미지들',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
